<?xml version="1.0"?>
<package format="3">
  <name>ackermann_odom</name>
  <version>0.0.1</version>
  <description>Odometry publisher from wheel linear velocity and steering angle.</description>
  <maintainer email="user@example.com">user</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
